### ISSUE TITLE
USA- wrong state id for several loc in Election GUI

### ISSUE THREAD

**Issue by CaelumW** [TNODevs/TNO-Bug-Tracker#1222]
### HOI4 version

v.1.12.3

### TNO version

v.1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### List the loc issues below

Wrong state ids for the following locs in **TNO_USA_elections_l_english.yml**

**Minnesota** _(ID: 391)_ - loc uses 381 (Wyoming)
USA_minnesota_seat_1_no_change_prev
USA_minnesota_seat_1_change_prev
USA_minnesota_seat_1_change_primaried_prev

USA_minnesota_seat_1_no_change
USA_minnesota_seat_1_change
USA_minnesota_seat_1_change_primaried

USA_minnesota_seat_2_no_change_prev
USA_minnesota_seat_2_change_prev
USA_minnesota_seat_2_change_primaried_prev

USA_minnesota_seat_2_no_change
USA_minnesota_seat_2_change
USA_minnesota_seat_2_change_primaried

USA_minnesota_seat_1_no_change_predictions
USA_minnesota_seat_1_change_prediction
USA_minnesota_seat_1_change_primaried_prediction

USA_minnesota_seat_2_no_change_predictions
USA_minnesota_seat_2_change_predictions
USA_minnesota_seat_2_change_primaried_prediction

**Louisiana** _(ID: 371)_ - loc uses 369 (Kentucky)
USA_louisiana_seat_1_no_change
USA_louisiana_seat_1_change_primaried
USA_louisiana_seat_2_change_primaried

**South Carolina** _(ID: 364)_ - loc uses 367 (Alabama)
USA_south_carolina_seat_1_change_predictions
USA_south_carolina_seat_1_change_primaried_prediction

USA_south_carolina_seat_2_change_predictions
USA_south_carolina_seat_2_change_primaried_prediction

**Utah** _(ID: 380)_ - loc uses 367 (Alabama)
USA_utah_seat_1_change_predictions
USA_utah_seat_1_change_primaried_prediction

USA_utah_seat_2_change_predictions
USA_utah_seat_2_change_primaried_prediction

**District of Columbia** _(ID: 992)_ - part of loc uses 954 (Delaware), also typo saying "Colombia" instead of "Columbia"
US_VOTE_DC_TOOLTIP
US_VOTE_DC_TOOLTIP_PREV

_("Colombia" Typo only)_
US_VOTE_DC_TOOLTIP_NAT_SUPPORT
US_VOTE_DC_TOOLTIP_NPP_SUPPORT
US_VOTE_DC_TOOLTIP_HOUSE_NOT_YET
US_VOTE_DC_TOOLTIP_HOUSE
US_VOTE_DC_TOOLTIP_HOUSE_PREDICTION

**Other typo**: "and the right now" (State NPP support breakdown)
US_voting_npp_l_npp_c_npp_fr_on_top
US_voting_npp_l_npp_c_npp_y_on_top
US_voting_npp_l_npp_fr_npp_y_on_top
US_voting_npp_c_npp_fr_npp_y_on_top

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by CaelumW** [comment]
Those two are still wrong in the new version, only it now uses 952 (Maine) lol
US_VOTE_DC_TOOLTIP
US_VOTE_DC_TOOLTIP_PREV

**Comment by runelead00** [comment]
Fixed in Dev Build, apologies for that

**Comment by CaelumW** [comment]
Sorry to bother again, but US_VOTE_DC_TOOLTIP and US_VOTE_DC_TOOLTIP_PREV still each have a last incorrect state id lol

![d1](https://user-images.githubusercontent.com/28941737/200473682-ac48a44b-b400-4375-bf25-86ed53caa6a8.jpg)
![d2](https://user-images.githubusercontent.com/28941737/200473688-e2045f5a-19f4-430a-812c-de04eb8da36b.jpg)
