### ISSUE TITLE
JAP - Issues with Azande winning Congo war

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#182]
- Operating System: windows 10
- HOI4 Version: latest
- TNO Version: 1.2.0a
- Any other mods in use: no
- Were you using Steam? yes
- Which expansions do you NOT have? i own them all

As Japan, I supported Azande and they won the congo war - however, the war never "resolved", and the foreign intervention tab in decisions never went away. They were no longer at war with anyone. I did receive a broken event with no localization when they won, but unfortunately I forgot to take a save.

**Comment by jink47787** [comment]
This may have been fixed as of hotfix 1.2.0c, as I saw some issues with the Congo conflict were addressed

**Comment by kolebaby12** [comment]
Currently playing TT on the latest patch on version 1.10.8, can confirm this issue still persists. The LOC seems to be fine, and they join your economic sphere, but it isn't removed from the global conflicts tab and you can still send supplies, military advisors and technical aid, from what I'm able to gather.

**Comment by ModdingAccount** [comment]
Fixed on dev build.
