### ISSUE TITLE
JAP - End of interregnum incorrectly removes "The Showa Emperor" modifier

### ISSUE THREAD

**Issue by jink47787** [TNODevs/TNO-Bug-Tracker#2264]
### Operating System

win11

### HOI4 version

1.12.14

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The Showa Emperor modifier is permanently removed once the interregnum ends.

### Steps to reproduce / Cause of the issue

The events jap_interregnum.70, jap_interregnum.78, and jap_interregnum.87 are mistakenly using the scripted effect JAP_remove_all_showa_ideas as a hidden effect, thus permanently removing the Showa Emperor modifier. Removing that scripted effect fixes the issue.

### Expected behaviour

The modifier is intended to be adjusted once a faction takes control, not removed.

**Comment by Jack121Q** [comment]
Thank you for the report. I am the guy who did the facelift, this has been fixed. Someone made that effect before on the day of release and he made a little mistake. My apologies.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by jink47787** [comment]
Hi! I know this was marked as fixed, but the bug is still present in version 1.5.0a. The edited scripted effect JAP_remove_all_showa_ideas_INT, which is supposed to avoid removing the PM specific Showa ideas when the new PM takes power, does not function correctly. 

While the bug does not occur when putting Takagi in power, it still removes the Showa idea if Ikeda or Kaya takes power. This is because the jap_showa_emperor_ikeda and jap_showa_emperor_kaya ideas are removed before the check on whether they _should_ be removed takes place. You can easily recreate this bug by triggering event jap_interregnum.1 (Yasuda Crisis event) and then triggering either Ikeda's election (jap_interregnum.70) or Kaya's election (jap_interregnum.78).

To fix this, the two lines I've marked in the screenshot below should be removed from JAP_remove_all_showa_ideas_INT:
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/59315866/a0cfd3e7-af84-4692-b690-99a7d3d8b5e2)

**Comment by Jack121Q** [comment]
> Hi! I know this was marked as fixed, but the bug is still present in version 1.5.0a. The edited scripted effect JAP_remove_all_showa_ideas_INT, which is supposed to avoid removing the PM specific Showa ideas when the new PM takes power, does not function correctly.
> 
> While the bug does not occur when putting Takagi in power, it still removes the Showa idea if Ikeda or Kaya takes power. This is because the jap_showa_emperor_ikeda and jap_showa_emperor_kaya ideas are removed before the check on whether they _should_ be removed takes place. You can easily recreate this bug by triggering event jap_interregnum.1 (Yasuda Crisis event) and then triggering either Ikeda's election (jap_interregnum.70) or Kaya's election (jap_interregnum.78).
> 
> To fix this, the two lines I've marked in the screenshot below should be removed from JAP_remove_all_showa_ideas_INT: ![image](https://user-images.githubusercontent.com/59315866/278501928-a0cfd3e7-af84-4692-b690-99a7d3d8b5e2.png)
> 
> EDIT: I thought commenting would reopen the issue, but I guess not. I am going to make a new issue report for this.

Hi, saw your reply and fixed that issue today. Thank you
