### ISSUE TITLE
Dem Komi Despot Stalina purges herself.

### ISSUE THREAD

**Issue by jonteboi0707** [TNODevs/TNO-Bug-Tracker#3069]
### Operating System

Windows 11

### HOI4 version

11.14.2

### TNO version

1.5.0c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When i try to purge shafy as stalina she accidentaly purges herself, and after that the purge menu shows that you can purge the democrats (like stalina and vozensensky).

### Steps to reproduce / Cause of the issue

1 Play komi
2 Get despot stalina
3 Try to purge shafy

### Expected behaviour

That i was going to get rid off shafy and not stalina.

### Screenshots

![20240318104027_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/146529932/5e14766a-ff68-4065-b786-578bfccbcc54)

### Additional information

And after that the purge menu shows that you can purge the democrats (like stalina and vozensensky). And personaly i think this has to do with that sometimes shafy is in the despot section.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by jonteboi0707** [comment]
She still gets purged.
![20240813211746_1](https://github.com/user-attachments/assets/17890e91-413a-4024-afde-f9fe06b19e92)
![20240813211758_1](https://github.com/user-attachments/assets/fa6e40b8-8662-4f5a-8e36-66d6ceea0b5c)
