### ISSUE TITLE
RPS - When the tag wins in the civil war, the game still sets no elections.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4137]
### Operating System

Windows 10

### HOI4 version

1.15.2

### TNO version

1.7.0a

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

The title. It's a democratic country so it should have elections.

### Steps to reproduce / Cause of the issue

Should the RPS tag win in the civil war.

### Expected behaviour

The game should set elections.

### Screenshots

![image](https://github.com/user-attachments/assets/238cd4f3-b5e7-458c-92bb-85f2a3eff8d4)

**Comment by Jack121Q** [comment]
Fixed. Thank you

**Comment by Marok132** [comment]
> Fixed. Thank you

Wait... how does it work? You rejected a similar issue with the SNI tag but fixed for the RPS one. Why?

**Comment by Jack121Q** [comment]
I don't see why SNI should have elections, maybe I missed something from their loc though.

**Comment by Marok132** [comment]
> I don't see why SNI should have elections, maybe I missed something from their loc though.
If I understand its lore properly, the SNI tag is still a democractic republic. So it would make sense to give them elections.

**Comment by Jack121Q** [comment]
Fixed

**Comment by Marok132** [comment]
> Fixed. Thank you

You didn't fix it brother.
![Image](https://github.com/user-attachments/assets/61627a6d-6f33-4ca2-a265-2a374e927ecd)

**Comment by Jack121Q** [comment]
I don't understand why the fix didn't work.

**Comment by Marok132** [comment]
> I don't understand why the fix didn't work.

Just set in set_politics "election_frequency, "elections_allowed and "last_election" in "RPS - Republic of Sudan" and don't f*ck your mind yourself with it. It should fix it.

![Image](https://github.com/user-attachments/assets/d39e4586-b9d5-4d32-9132-50b123f21b4e)

**Comment by Jack121Q** [comment]
Fixed?
