### ISSUE TITLE
SYR - Change tag's economy type to Dirigisme if Socnats take power.

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#4580]
### HOI4 version

1.16

### TNO version

1.7.0b

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

The title.

### Justifications

Such regimes, usually, don't use capitalism as a main economic platform. I think Dirigisme would work better here.

### Screenshots

![Image](https://github.com/user-attachments/assets/9ae4c6bb-530f-400c-9eb9-77b8fa4ca422)

**Comment by Jack121Q** [comment]
Fixed, thank you. They will use Planned Economy.

**Comment by AvataTa** [comment]
> Fixed, thank you. They will use Planned Economy.

It is not fixed.

![Image](https://github.com/user-attachments/assets/e068f530-7ac8-4bd5-bcfa-d5728dcf1196)
