### ISSUE TITLE
Guangdong - Debt Ceiling Set to 0 for No Reason

### ISSUE THREAD

**Issue by davigk19** [TNODevs/TNO-Bug-Tracker#4847]
### Operating System

Windows 11 

### HOI4 version

TNO v1.7.0b 

### TNO version

Countenance v1.16.5.e690 (e3d8) (S)

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

For some reason, after a certain period of time, around December 1962 to January 1963, Guangdong's debt ceiling comes crashing down from approximately 450% to 0%, which doesn't seem right at all, and causes pretty much permanent financial crisis for me, and I have no idea why this should be happening, and by 1965 it caused my economy to take a massive hit that I don't think is normal

### Steps to reproduce / Cause of the issue

Play the game for about a year, that's about it

### Expected behaviour

For the debt ceiling to remain the same, around 400%, or whatever is a reasonable amount to not have constant financial crisis, so that Guangdong can have a functional economy with regards to all the crises it has normally

### Screenshots

![Image](https://github.com/user-attachments/assets/fc19a6d6-2dcf-4f4e-bae0-bd17c6d879ad)

**Comment by Marok132** [comment]
It was fixed in dev build brother.

**Comment by davigk19** [comment]
I loaded a game and redownloaded the mod, and it still eventually happened; in 1964 instead, but it still happened

**Comment by Marok132** [comment]
> I loaded a game and redownloaded the mod, and it still eventually happened; in 1964 instead, but it still happened

I meant it was fixed in dev build, not the public one.
