### ISSUE TITLE
GER/KOM - Germania Rules The Waves Focus Causes CTD Due to Naval Leader Reassignment

### ISSUE THREAD

**Issue by jmaloy97** [TNODevs/TNO-Bug-Tracker#489]
**Questions**

- Operating System: Arch Linux 64-bit (kernel ver 5.16.1-arch1-1)
- HOI4 Version: v1.11.4.e26e (b22c)
- TNO Version: Latest version as of January 22, 2022 --> "Jan 21, 2022 @ 6:59pm"
- Any other mods in use:
	"Map Modes+"
	"Precise Buffs - Cheat Ideas"
	"Tool Pack Updated 2021"

- Were you using Steam? Yes
- Which expansions do you NOT have? None

**Longer Description of Issue:**
The "Germania Rules the Waves" focus for Speer's Germany seems to cause a crash whenever it completes. My save game is currently on January 2, 1967 - Speer's Germany is working on the focus "Germania Rules the Waves" (id = GER_germania_rules_the_waves) that has one day left. When the focus completes at 1:00 on the following day (3 January 1967), some of the logic involved in the issue breaks the game and causes a CTD.

**Steps to Reproduce/Cause Issue:**
1. Play game (I am playing as Ordosocialist Komi, but I don't believe that has any bearing on the issue at all)
2. Wait until Speer's Germany completes the focus in question, at the end of the naval section of their post-civil war tree.
3. Game should CTD consistently.

**Screenshots:**
![image](https://user-images.githubusercontent.com/50754569/150665131-28afbe1f-c15f-455a-b768-59ba8eca4eca.png)

My diagnosis of the issue seems to show that the following section of the focus is the cause of the error, as omitting it from the game files causes the error to not occur:

		_GER_friedrich_guggenberger = {
			set_nationality = GER
			add_naval_commander_role = {
				traits = { war_hero sea_wolf }
				skill = 4
				attack_skill = 4
				defense_skill = 3
				maneuvering_skill = 1
				coordination_skill = 1
				legacy_id = 130
			}
			promote_leader = yes
		}
		GER_otto_ites = {
			set_nationality = GER
			add_naval_commander_role = {
				traits = { war_hero blockade_runner }
				skill = 2
				attack_skill = 2
				defense_skill = 2
				maneuvering_skill = 1
				coordination_skill = 1
				legacy_id = 147
			}
			promote_leader = yes
		}_

After removing the above section from the Speer focus tree, the game proceeds without issue:
![image](https://user-images.githubusercontent.com/50754569/150665209-09a8a86a-ea4e-4806-b831-242b34a75e0a.png)
![image](https://user-images.githubusercontent.com/50754569/150665211-d3349085-e4cd-4734-9977-9f8f18441728.png)

**Game Saves and Log Files, if possible:**
from game.log:
[23:37:16][frontend.cpp:654]: 

		[[ Launching SINGLEPLAYER-game ]]
	Start-date: 1967.1.2.1

[23:37:17][ingameidler.cpp:4859]: Start RestoreDeviceObjects
[23:37:20][ingameidler.cpp:5007]: End RestoreDeviceObjects
[23:39:18][effectbase.cpp:2149]:  2:00, 2 January, 1967: Kemerovo: Decision KEM_unlock_lydia_decisions
[23:39:18][effectbase.cpp:2149]:  3:00, 2 January, 1967: Kemerovo: Decision KEM_disable_lydia_decisions
**[23:39:19][effectbase.cpp:2149]:  1:00, 3 January, 1967: Großgermanisches Reich: Focus GER_germania_rules_the_waves**

**Comment by tkgitno** [comment]
Fixed in Dev Build

**Comment by jmaloy97** [comment]
This bug still persists for me in NSB Hotfix A, just for dev awareness
