### ISSUE TITLE
Every country - The game crashes after loading

### ISSUE THREAD

**Issue by Yockieite** [TNODevs/TNO-Bug-Tracker#650]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.11.8
- TNO Version: 1.2.0
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all the expansions

**Longer Description of Issue:**
Whenever I select a nation and start up said nation, the game loads up the info panel for the nation and then shortly after before I can press any button, it crashes regardless if I have the low graphical settings on or not

**Steps to Reproduce/Cause Issue:**

1. Start up the game

2. Select a nation

3. Wait for the nation to load the info panel

**Screenshots:**

**Game Saves and Log Files, if possible:**

**Comment by masterbobli** [comment]
Please specify the HOI4 version and TNO version

**Comment by Yockieite** [comment]
done

**Comment by runelead00** [comment]
Consolidated in single list with similar crashes, not yet fixed and cause currently unknown
